---
apiVersion: v1
kind: Namespace
metadata:
  name: testing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing
  name: test
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: jlrine2/testing
        imagePullPolicy: Always
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: test
  labels:
    app: test
spec:
  selector:
    app: test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
